nome = 'Gabriel da Silva'
print(nome)
print('Gabriel' in nome)
nome = nome.replace('Gabriel', 'Lucas')
print(nome)
print('Gabriel' in nome)
print(nome.lower().find('silva'))
dividido = nome.split()
print(dividido[0][3])
print(nome.capitalize())
print(nome.title())
print(nome.strip())
